include: package:theodo_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "example/**"
  
linter:
  rules:
    # Not mandatory since this is not a sdk
    public_member_api_docs: false
    # Convignent for null safety checks of field in fucntion
    no_leading_underscores_for_local_identifiers: false
    # It has no sence for a state notifier
    avoid_setters_without_getters: false
    # Taken care of by dcm
    avoid_positional_boolean_parameters: false
    # False positive
    cascade_invocations: false
    # Not usefull
    comment_references: false

dart_code_metrics:
  assists:
    wrap-with:
      - Scaffold:
          prop: body
          list: false
      - Stack:
          prop: children
          list: true
  rules:
    - avoid-inferrable-type-arguments
    - no-equal-arguments: false
    - prefer-correct-handler-name: false
    - arguments-ordering:
        alphabetize: false
        last:
          - child
          - children

