include: package:theodo_analysis/analysis_options.yaml

analyzer:
  exclude:
  
linter:
  rules:
    # Not mandatory since this is not a sdk
    public_member_api_docs: false
    # It has no sence for a state notifier
    avoid_setters_without_getters: false
    # Not usefull
    comment_references: false

dart_code_metrics:
  assists:
    wrap-with:
      - Scaffold:
          prop: body
          list: false
      - Stack:
          prop: children
          list: true
  rules:
    - no-equal-arguments: false
    - prefer-correct-handler-name: false
    - arguments-ordering: false
    - member-ordering: false
    - avoid-collection-mutating-methods: false
    - prefer-correct-callback-field-name: false
    - match-getter-setter-field-names: false
    - prefer-typedefs-for-callbacks: false
    - prefer-prefixed-global-constants: false
    - prefer-correct-setter-parameter-name: false

