name: dojo_workspace
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.19.6"

dev_dependencies:
  melos: ^3.1.0
  theodo_analysis:
    git:
      url: https://github.com/bamlab/theodo_analysis.git
      ref: 8ea6cd0f0c4df81edefef940ee7ff61ac5458e52
