name: dojo_workspace
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.19.6"

dev_dependencies:
  bam_analysis:
    git:
      url: https://github.com/bamlab/bam_analysis.git
      ref: 98176cdbaf95a8cd089752076debbe0c08787418
  melos: ^3.1.0
