name: flutter_dojo_apps
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  animated_clipper: ^0.2.0+2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bam_theme:
    path: "../theme"
  flutter_cache_manager: ^3.3.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  gradient_borders: ^1.0.0
  responsive_navigation_bar: ^4.0.4
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.2
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  adaptive_test: ^0.4.0
  bam_analysis:
    git:
      url: https://github.com/bamlab/bam_analysis.git
      ref: 98176cdbaf95a8cd089752076debbe0c08787418
  build_runner: ^2.4.10
  ci: ^0.1.0
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/Background.png
    - assets/play_icon.svg
    - assets/logo.png
