name: dojo_widgetbook
description: Design System preview
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.16.2"

dependencies:
  collection: ^1.18.0
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bam_theme:
    path: ../theme
  flutter_cache_manager: ^3.3.2
  flutter_masonry_view: ^0.0.2
  reactive_forms: ^16.1.0
  widgetbook: ^3.0.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  theodo_analysis:
    git:
      url: https://github.com/bamlab/theodo_analysis.git
      ref: 8ea6cd0f0c4df81edefef940ee7ff61ac5458e52
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.0.0


flutter:
  uses-material-design: true
