name: flutter_bam_theme
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  cached_network_image: ^3.3.0
  capped_progress_indicator: ^0.0.2
  dismissible_page: ^1.0.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  modal_bottom_sheet:
    git:
      path: modal_bottom_sheet
      url: https://github.com/bamlab/modal_bottom_sheet.git
      ref: 91d6e2496fe3a138f0810ba2733bf718ed167b3d
  photo_view: ^0.14.0
  progressive_image:
    git:
      url: https://github.com/bamlab/progressive_image.git
  reactive_forms: ^16.1.1
  sliver_tools: ^0.2.12
  video_player: ^2.8.1

dev_dependencies:
  adaptive_test: ^0.4.1
  build_runner: ^2.4.10
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  theodo_analysis:
    git:
      url: https://github.com/bamlab/theodo_analysis.git
      ref: 8ea6cd0f0c4df81edefef940ee7ff61ac5458e52
  video_player_platform_interface: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Montserrat_Black
      fonts:
        - asset: fonts/Montserrat_Black.ttf
          weight: 900
    - family: theme_icons
      fonts:
        - asset: fonts/theme_icons.otf
    - family: Arcadienne
      fonts:
        - asset: fonts/Arcadienne-Brush.otf
          weight: 600
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Regular.ttf
          weight: 600
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-Regular.ttf
        - asset: fonts/ZillaSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/ZillaSlab-Bold.ttf
          weight: 700
